### ISSUE TITLE
Outdated localvimrc plugin causing syntax error

### ISSUE THREAD

**Issue by unimpossible** [drmikehenry/vimfiles#209]
On vim (8.2) getting a syntax warning while parsing the localvimrc plugin. Looks like it's been fixed upstream in this commit https://github.com/embear/vim-localvimrc/commit/7974cd487213372a089acbcd01dd8e851fc16620.

I can also manually patch bundle/localvimrc/plugin/localvimrc.vim:
```
-          catch ^Vim\%((\a\+)\)\=:E48
+          catch /^Vim\%((\a\+)\)\=:E48/
```

Cheers!

**Comment by drmikehenry** [comment]
Thanks; I hadn't upgraded past Vim 8.2.73, so I hadn't seen the issue.  I was able to replicate it, and upgrading localvimrc fixed the problem as you suggested.  I appreciate the notification :-)
